import type { Metadata } from "next";
import {
  Manrope,
  Covered_By_Your_Grace,
  Rock_Salt,
  Audiowide
} from "next/font/google";import "./globals.css";

// const audiowide = Audiowide({ subsets: ["latin"], weight: "400" });
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
export const rockSalt = Rock_Salt({
  weight: "400",
  subsets: ["latin"],
});
export const covered = Covered_By_Your_Grace({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} h-full antialiased`}
    >
      <body className={` ${covered.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
